from typing import Any

import pytest

from sbomgrader.core.documents import Document
from sbomgrader.core.formats import SBOMFormat
from sbomgrader.translate.translation_map import TranslationMap
from sbomgrader.core.utils import get_mapping


def ordered(obj: Any):
    """Orders lists so translation is not order-dependent."""
    if isinstance(obj, dict):
        return sorted((k, ordered(v)) for k, v in obj.items())
    if isinstance(obj, list):
        return sorted(ordered(x) for x in obj)
    else:
        return obj


class ComparableDoc:
    def __init__(self, doc: Document):
        self.document = doc

    def __eq__(self, other):
        if not isinstance(other, ComparableDoc) or not isinstance(other, Document):
            raise TypeError(
                f"Cannot compare object of type {self.__class__.__name__} to an object  of type {other.__class__.__name__}."
            )


@pytest.mark.parametrize(["spdx"], [("spdx23",), ("spdx22",)])
@pytest.mark.parametrize(["cyclonedx"], [("cdx16",), ("cdx15",)])
def test_translation(cyclonedx, spdx):
    tm = TranslationMap.from_file(
        "tests/testdata/test_translation/sample_spdx23_cdx16.yml"
    )
    first_doc = Document(
        get_mapping(f"tests/testdata/test_translation/sample_{spdx}.json")
    )
    second_doc = Document(
        get_mapping(f"tests/testdata/test_translation/sample_{cyclonedx}.json")
    )
    assert tm.convert(first_doc, SBOMFormat(cyclonedx)).doc == second_doc.doc
    assert tm.convert(second_doc, SBOMFormat(spdx)).doc == first_doc.doc


def test_spdx_product_translation():
    spdx_doc = Document.from_file(
        "tests/testdata/test_translation/actual_data/rhel-9.2-eus.spdx.json"
    )
    tr_map = TranslationMap.from_file(
        "sbomgrader/translation_maps/sample_spdx23_cdx16.yml"
    )
    new_doc = tr_map.convert(tr_map.convert(spdx_doc))
    for doc in spdx_doc, new_doc:
        # Ignore these autogenerated fields:
        doc.doc.pop("documentNamespace")
        creators = doc.doc.get("creationInfo").get("creators")
        creators = [c for c in creators if not c.startswith("Tool: SBOMGrader")]
        doc.doc["creationInfo"]["creators"] = creators
    assert ordered(spdx_doc.doc) == ordered(new_doc.doc)
