---
MUST:
  # general
  - Document passes schema validation
SHOULD:
  # general
  - All named packages have a versionInfo
  - License list has correct form
  - Creation time is valid
  - All packages are referenced in relationships
  - All packages have a supplier
  # specific
  - Number of packages is greater than 1
  - Main element has cpe22 locator
  - Non-main elements have a purl with arch and repository_id qualifiers
MAY:
  # general
  - All files SPDXIDs have format SPDXRef-File-filename-digest
rulesets:
  - general
  - specific
